---
title: "Analysis"
---

```{r}
library(babynames)
library(knitr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(pheatmap)
```

# cars example

```{r}
#| label: "fig-mpg-vs-drat"
#| fig-cap: "mpg versus drat"
#| fig-align: "left"
library(ggplot2)
mtcars |>
  ggplot(aes(x = drat, y = mpg)) + geom_point() + theme_bw()
```

From @fig-mpg-vs-drat you can see there is a positive correlation.

# baby names

## data sample

```{r}
head(babynames) |> kable()
```

## functions

```{r}

get_most_frequent <- function(babynames, select_sex, from = 1950) {
  most_freq <- babynames |>
    filter(sex == select_sex, year > from) |>
    group_by(name) |>
    summarise(average = mean(prop)) |>
    arrange(desc(average))
    
  return(list(
    babynames = babynames,
    most_frequent = most_freq,
    sex = select_sex,
    from = from))
}

plot_top <- function(x, top = 10) {
  topx <- x$most_frequent$name[1:top]
  
  p <- x$babynames |>
    filter(name %in% topx, sex == x$sex, year > x$from) |>
    ggplot(aes(x = year, y = prop, color = name)) +
    geom_line() +
    scale_color_brewer(palette = "Paired") +
    theme_classic()
  
  return(p)
}

```

## report 1

```{r}
#| label: "fig-baby-f"
#| fig-cap: "Frequent female names"
#| fig-align: "right"
get_most_frequent(babynames, select_sex = "F") |>
  plot_top()
```

From @fig-baby-f we can see...

## report 2

```{r}
#| label: "fig-baby-m"
#| fig-cap: "Frequent male names"
#| fig-align: "right"
get_most_frequent(babynames, select_sex = "M") |>
  plot_top()
```

## report 3

```{r}
#| label: "fig-baby-f-var"
#| fig-cap: "Frequent female names from 2010"
#| fig-align: "right"
from_year <- 2010
# get most frequent girl names from 2010 onwards
most_freq_girls <- get_most_frequent(babynames, select_sex = "F",
                                     from = from_year)

# plot top girl names
most_freq_girls |>
  plot_top(top = 5)
```

## report 4

```{r}
#| label: "fig-baby-f-heat"
#| fig-cap: "Frequent female names"
#| fig-align: "right"
# get top 30 girl names in a matrix
# with names in rows and years in columns
prop_df <- babynames |> 
  filter(name %in% most_freq_girls$most_frequent$name[1:30] & sex == "F") |>
  filter(year >= from_year) |> 
  select(year, name, prop) |>
  pivot_wider(names_from = year,
              values_from = prop)


prop_mat <- as.matrix(prop_df[, 2:ncol(prop_df)])
rownames(prop_mat) <- prop_df$name

# create heatmap
pheatmap(prop_mat, cluster_cols = FALSE, scale = "row")
```


## report 5

```{r}
#| label: fig-line-2010
#| layout: [[50,50], [100]]
#| fig-cap: "Most popular girl names from 2010 onwards"
#| fig-subcap: 
#|   - "Top 5"
#|   - "Top 10"
#|   - "Top 30"
# get most frequent girl names from 2010 onwards
from_year <- 2010
most_freq_girls <- get_most_frequent(babynames, select_sex = "F",
                                     from = from_year)

# plot top 5 girl names
most_freq_girls |>
  plot_top(top = 5)

# plot top 10 girl names
most_freq_girls |>
  plot_top(top = 10)

# get top 30 girl names in a matrix
# with names in rows and years in columns
prop_df <- babynames |> 
  filter(name %in% most_freq_girls$most_frequent$name[1:30] & sex == "F") |>
  filter(year >= from_year) |> 
  select(year, name, prop) |>
  pivot_wider(names_from = year,
              values_from = prop)

prop_mat <- as.matrix(prop_df[, 2:ncol(prop_df)])
rownames(prop_mat) <- prop_df$name

# create heatmap
pheatmap(prop_mat, cluster_cols = FALSE, scale = "row")
```
In @fig-line-2010-1 and @fig-line-2010-2 the line plots are shown. To view trends of many names at once, @fig-line-2010-3 displays a heatmap.

